# Configuration file for the hungry-daemons project

[env]
initial_population  =  10
max_population      =  500
simulation_ticks    =  1000
max_cpu_tokens      =  100
life_expectancy     =  20
ticks_per_s         =  2
