# Configuration file for the hungry-daemons project

[env]
initial_population    = 40
max_population        = 5000
simulation_ticks      = 1000
max_cpu_tokens        = 1000
life_expectancy       = 20
ticks_per_s           = 20

[genome]
min_cpu_hunger        = 10
max_cpu_hunger        = 500

min_replication_rate  = 1
max_replication_rate  = 5

min_mutation_chance   = 0.03
max_mutation_chance   = 0.5

min_life_without_food = 15
max_life_without_food = 40

min_lifespan_ratio    = 0.60
max_lifespan_ratio    = 1.00

min_hold_time         = 1
max_hold_time         = 4

# EDITORS SORTIED ROISTED STORIED TRIODES
# NITREOUS
