// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed .\fighting_gophers.png
var resourceIconData []byte
var resourceIcon = &fyne.StaticResource{
	StaticName:    ".\\fighting_gophers.png",
	StaticContent: resourceIconData,
}
