[env]
initial_population    = 100
max_population        = 3000
simulation_ticks      = 200
max_cpu_tokens        = 1000
life_expectancy       = 500
ticks_per_s           = 10

[genome]
min_cpu_hunger        = 5
max_cpu_hunger        = 50

min_replication_rate  = 1
max_replication_rate  = 4

min_mutation_chance   = 0.01
max_mutation_chance   = 0.10

min_life_without_food = 50
max_life_without_food = 150

min_lifespan_ratio    = 0.80
max_lifespan_ratio    = 1.00

min_hold_time         = 1
max_hold_time         = 3

[simulation]
death_prob        = 0.012
replication_prob  = 0.07
cpu_release_prob  = 0.80
