[env]
initial_population    = 100
max_population        = 2000
simulation_ticks      = 500
max_cpu_tokens        = 50
life_expectancy       = 30
ticks_per_s           = 20

[genome]
min_cpu_hunger        = 50
max_cpu_hunger        = 1000

min_replication_rate  = 1
max_replication_rate  = 2

min_mutation_chance   = 0.10
max_mutation_chance   = 0.90

min_life_without_food = 2
max_life_without_food = 5

min_lifespan_ratio    = 0.20
max_lifespan_ratio    = 0.50

min_hold_time         = 5
max_hold_time         = 20
